- hosts: localhost
  tasks:
    - name: POC DDS BMC Remedy - Descoberta de servico
      anadds_proc:
        ChangeID: CHG000006792500
        Status: WorkInProgress
      register: result
    - debug: var=result